version: "3"
services:
  ppm-server:
    container_name: ppm-server
    restart: always
    # build: .
    image: megoworkdevteam/ppm-server
    ports:
      - "1337:1337"
    volumes:
      - .:/app
    links:
      - mongo
    # depends_on: 
    #   - mongo
    environment:
    - NODE_ENV=production
  # mongo:
  #   container_name: mongo
  #   image: mongo
  #   volumes:
  #     - ./data:/data/db
  #   ports:
  #     - "27017:27017"
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
  ppm-client: 
    image: megoworkdevteam/ppm-client
    ports:
      - "4200:4200"
    depends_on: 
      - ppm-server
    restart: always
volumes:
  mongodata: