version: "3"
services:
  ppm-server:
    container_name: ppm-server
    restart: always
    build: .
    ports:
      - "1337:1337"
    volumes:
      - .:/app
    links:
      - mongo
    depends_on: 
      - mongo
    environment:
    - NODE_ENV=production
  # mongo:
  #   container_name: mongo
  #   image: mongo
  #   volumes:
  #     - ./data:/data/db
  #   ports:
  #     - "27017:27017"
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
volumes:
  mongodata: